# Generated by Django 6.0.7 on 2026-10-01 05:44

import django.db.models.deletion
import todo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('study', 'Study'), ('work', 'Work'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('health', 'Health'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#d94c4c', 'Red'), ('#df7b32', 'Orange'), ('#d6aa2b', 'Yellow'), ('#4a9a62', 'Green'), ('#4285b5', 'Blue'), ('#7654a3', 'Purple'), ('#c24d70', 'Pink'), ('#8b5e3c', 'Brown'), ('#87939b', 'Gray')], default='#d46b32', max_length=7),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/', validators=[todo.models.validate_image_upload])),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/%Y/%m/', validators=[todo.models.validate_image_upload])),
                ('background_color', models.CharField(choices=[('#ffffff', 'White'), ('#f6efe3', 'Cream'), ('#e7d6c5', 'Beige'), ('#8b5e3c', 'Brown'), ('#3f2d24', 'Dark Brown'), ('#eef1f3', 'Light Gray'), ('#dcecf7', 'Blue'), ('#dcefe1', 'Green'), ('#ebe3f7', 'Lavender'), ('#f8dfe6', 'Pink')], default='#f6efe3', max_length=7)),
                ('accent_color', models.CharField(choices=[('#8b5e3c', 'Brown'), ('#1f2522', 'Black'), ('#2774ae', 'Blue'), ('#367a56', 'Green'), ('#7654a3', 'Purple'), ('#c24d70', 'Pink'), ('#d46b32', 'Orange'), ('#287f7c', 'Teal')], default='#8b5e3c', max_length=7)),
                ('default_task_color', models.CharField(default='#d46b32', max_length=7)),
                ('default_priority', models.CharField(default='medium', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
