# Generated by Django 6.0.7 on 2026-10-01 06:22

import django.db.models.deletion
import todo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_category_task_color_task_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#d46b32', max_length=7, validators=[todo.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#8b5e3c', max_length=7, validators=[todo.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#f6efe3', max_length=7, validators=[todo.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_task_color',
            field=models.CharField(default='#d46b32', max_length=7, validators=[todo.models.validate_hex_color]),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_category_per_user')],
            },
        ),
    ]
