# Generated by Django 6.0.7 on 2026-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_category_alter_task_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categories_seeded',
            field=models.BooleanField(default=False),
        ),
    ]
