# Generated by Django 6.0.7 on 2026-10-01 06:46

import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_userprofile_categories_seeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surface_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[todo.models.validate_hex_color]),
        ),
    ]
